/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container":          "#efedf1",
        "secondary":                  "#1960a3",
        "surface-container-low":      "#f4f3f7",
        "on-tertiary-fixed":          "#001d37",
        "on-background":              "#1a1c1e",
        "surface-container-lowest":   "#ffffff",
        "inverse-surface":            "#2f3033",
        "on-surface-variant":         "#43474e",
        "tertiary-container":         "#003762",
        "on-tertiary-container":      "#58a2f0",
        "on-secondary":               "#ffffff",
        "surface-container-highest":  "#e3e2e6",
        "tertiary-fixed-dim":         "#9fcaff",
        "background":                 "#faf9fd",
        "on-secondary-container":     "#00477f",
        "error":                      "#ba1a1a",
        "on-primary":                 "#ffffff",
        "on-secondary-fixed":         "#001c38",
        "secondary-container":        "#7db6ff",
        "tertiary-fixed":             "#d2e4ff",
        "primary-fixed-dim":          "#adc7f7",
        "inverse-primary":            "#adc7f7",
        "on-tertiary":                "#ffffff",
        "on-secondary-fixed-variant": "#004881",
        "primary-fixed":              "#d6e3ff",
        "surface-tint":               "#455f88",
        "outline-variant":            "#c4c6cf",
        "tertiary":                   "#00213e",
        "on-primary-container":       "#86a0cd",
        "surface-container-high":     "#e9e7eb",
        "on-surface":                 "#1a1c1e",
        "secondary-fixed-dim":        "#a2c9ff",
        "surface-bright":             "#faf9fd",
        "on-primary-fixed-variant":   "#2d476f",
        "primary":                    "#002045",
        "on-primary-fixed":           "#001b3c",
        "surface-variant":            "#e3e2e6",
        "on-error-container":         "#93000a",
        "on-error":                   "#ffffff",
        "primary-container":          "#1a365d",
        "inverse-on-surface":         "#f1f0f4",
        "on-tertiary-fixed-variant":  "#00497e",
        "surface-dim":                "#dad9dd",
        "surface":                    "#faf9fd",
        "error-container":            "#ffdad6",
        "secondary-fixed":            "#d3e4ff",
        "outline":                    "#74777f"
      },
      fontFamily: {
        heading:        ["Inter", "sans-serif"],
        display:        ["Inter", "sans-serif"],
        "display-mobile": ["Inter", "sans-serif"],
        body:           ["Inter", "sans-serif"],
        small:          ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
