/**
 * applyTagMerge.ts
 * Applies the approved tag merge (see tagMerge.ts and tagApply.ts) to the database.
 *
 *   npm run ingest:tags-apply -- --write-map   regenerate src/ingestion/tagRenames.ts from the current tags (BEFORE applying)
 *   npm run ingest:tags-apply                  plan only: checks, backup, and what would change; changes nothing
 *   npm run ingest:tags-apply -- --apply       back up Tag and the scheme-tag links, merge in ONE transaction, prove it
 *
 * The merge uses the committed map (tagRenames.ts), so running it again later finds nothing left to do. The
 * transaction rolls back if any scheme would lose a tag or gain one it did not have.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import prisma from '../db/prisma.js';
import { hi } from '../translation/vocabulary/hi.js';
import { applyTagMerge, unresolvedVocabulary, type Backup, type LinkRow, type TagRow, type TagStore, type TagStoreTx } from './tagApply.js';
import { planMerges } from './tagMerge.js';
import { TAG_RENAMES } from './tagRenames.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPORTS = path.join(__dirname, '..', '..', 'reports');

type Db = Pick<typeof prisma, '$queryRaw' | '$executeRaw'>;

function readOps(db: Db): Omit<TagStore, 'transaction'> {
  return {
    async loadTags() {
      return db.$queryRaw<TagRow[]>`select id, name from "Tag" order by name`;
    },
    async loadLinks() {
      return db.$queryRaw<LinkRow[]>`select "A" as "schemeId", "B" as "tagId" from "_SchemeToTag"`;
    },
    async countSchemes() {
      const r = await db.$queryRaw<Array<{ n: number }>>`select count(*)::int as n from "Scheme"`;
      return r[0].n;
    },
  };
}

const store: TagStore = {
  ...readOps(prisma),
  transaction: (work) =>
    prisma.$transaction(
      async (tx) => {
        const txStore: TagStoreTx = {
          ...readOps(tx as Db),
          async mergeTag(fromId, toId) {
            // schemes that already carry the target keep their one link; the rest move over. Deleting the old tag
            // removes its remaining links too (the link table cascades).
            await tx.$executeRaw`insert into "_SchemeToTag" ("A", "B") select "A", ${toId} from "_SchemeToTag" where "B" = ${fromId} on conflict do nothing`;
            await tx.$executeRaw`delete from "Tag" where id = ${fromId}`;
          },
        };
        return work(txStore);
      },
      { timeout: 120_000, maxWait: 20_000 },
    ),
};

async function writeBackup(backup: Backup): Promise<void> {
  fs.mkdirSync(REPORTS, { recursive: true });
  const file = path.join(REPORTS, `tag-backup-${backup.takenAt.replace(/[:.]/g, '-')}.json`);
  fs.writeFileSync(file, JSON.stringify(backup));
  const back = JSON.parse(fs.readFileSync(file, 'utf8')) as Backup;
  if (back.tags.length !== backup.tags.length || back.links.length !== backup.links.length) throw new Error('backup file does not match what was read');
  console.log(`backup written and read back: ${path.relative(path.join(__dirname, '..', '..'), file)} (${back.tags.length} tags, ${back.links.length} links, ${back.schemeCount} schemes)`);
}

async function writeMap(): Promise<void> {
  const tags = await store.loadTags();
  const links = await store.loadLinks();
  const count = new Map<string, number>();
  for (const l of links) count.set(l.tagId, (count.get(l.tagId) ?? 0) + 1);
  const hindi = hi.tags as Record<string, string>;
  const plan = planMerges(tags.map((t) => ({ name: t.name, schemeCount: count.get(t.id) ?? 0, hindi: hindi[t.name] })));
  const entries = Object.entries(plan.renames).sort(([a], [b]) => a.localeCompare(b, 'en'));
  if (entries.length === 0) throw new Error('the current tags have nothing to merge; refusing to overwrite tagRenames.ts with an empty map');
  const body = entries.map(([from, to]) => `  ${JSON.stringify(from)}: ${JSON.stringify(to)},`).join('\n');
  const file = path.join(__dirname, 'tagRenames.ts');
  fs.writeFileSync(
    file,
    `// GENERATED by \`npm run ingest:tags-apply -- --write-map\` from the tag clean-up that was reviewed and approved.\n// Each key is a tag name that is merged away; each value is the name it becomes. Do not edit by hand.\n// Used by the merge itself and by ingestion (tagCanonical.ts), so re-running ingestion cannot bring duplicates back.\nexport const TAG_RENAMES: Record<string, string> = {\n${body}\n};\n`,
  );
  console.log(`wrote ${entries.length} renames to src/ingestion/tagRenames.ts`);
}

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  if (args.has('--write-map')) return writeMap();

  const renames = TAG_RENAMES;
  if (Object.keys(renames).length === 0) throw new Error('src/ingestion/tagRenames.ts is empty: run with --write-map first');

  // Warn about duplicates the approved map does not know about (new data since the review); they are not touched.
  const tags = await store.loadTags();
  const known = new Set(Object.keys(renames));
  const fresh = planMerges(tags.map((t) => ({ name: t.name, schemeCount: 0 }))).renames;
  // counts are not loaded here, so the kept side may differ from the approved map; only a pair the map never mentions is new
  const mentioned = new Set([...known, ...Object.values(renames)]);
  const unknown = Object.entries(fresh).filter(([from, to]) => !mentioned.has(from) && !mentioned.has(to));
  if (unknown.length > 0) console.log(`note: ${unknown.length} duplicate tag(s) in the database are not in the approved map and will be left alone: ${unknown.slice(0, 5).map(([f, t]) => `${f} => ${t}`).join(', ')}`);

  const apply = args.has('--apply');
  const proof = await applyTagMerge(store, renames, { writeBackup, dryRun: !apply });
  console.log(apply ? 'MERGE APPLIED (one transaction, proof passed inside it):' : 'PLAN ONLY (nothing changed):');
  console.log(JSON.stringify(proof, null, 1));

  if (apply) {
    // Independent check after the commit, from a fresh read.
    const after = await store.loadTags();
    const names = new Set(after.map((t) => t.name));
    const vocab = hi.tags as Record<string, string>;
    const bad = unresolvedVocabulary(Object.keys(vocab), renames, names, vocab);
    console.log(`Hindi vocabulary: ${Object.keys(vocab).length} entries, ${bad.length} unresolved`);
    bad.forEach((b) => console.log('  UNRESOLVED', b));
    const stillThere = Object.keys(renames).filter((n) => names.has(n));
    console.log(`merged-away names still present as tags: ${stillThere.length}`);
    if (bad.length > 0 || stillThere.length > 0) process.exitCode = 1;
  }
}

main()
  .catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
