import { Scheme } from '../types';

/**
 * Offline/no-backend mock dataset for VITE_USE_MOCK_DATA=true (the README's
 * documented default dev setup). Was previously an empty array, meaning mock
 * mode showed a blank app — see the commit that added this file.
 *
 * A representative sample (~36 schemes), not the full ~4,722-row real dataset
 * — this exists so frontend dev doesn't require Postgres running. Content is
 * illustrative/simplified for demo purposes, based on well-known public Indian
 * government scheme names, not verbatim official text. `deadline` is
 * deliberately left as 'Ongoing' on every entry — enrichScheme() in
 * schemeService.ts replaces that with its own generated placeholder date.
 */
export const MOCK_SCHEMES: Scheme[] = [
  // ── Agriculture ─────────────────────────────────────────────
  {
    id: 'mock-pm-kisan',
    name: 'PM Kisan Samman Nidhi',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmkisan',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmkisan',
    description: 'Income support of ₹6,000 per year to all land-holding farmer families, paid in three equal installments of ₹2,000 every four months directly into bank accounts.',
    shortDesc: 'Income support of ₹6,000/year to land-holding farmer families.',
    level: 'Central',
    authorityName: 'Ministry Of Agriculture and Farmers Welfare',
    ministry: 'Ministry Of Agriculture and Farmers Welfare',
    tags: ['Farmer', 'Agriculture', 'Financial Assistance', 'Direct Benefit Transfer'],
    categories: ['Agriculture'],
    category: 'Agriculture',
    benefit: '₹6,000 per year in 3 installments',
    deadline: 'Ongoing',
    featured: true,
    totalBeneficiaries: '11 Crore+',
    disbursed: '₹2.8 Lakh Cr+',
  },
  {
    id: 'mock-pmfby',
    name: 'Pradhan Mantri Fasal Bima Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmfby',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmfby',
    description: 'Crop insurance scheme providing financial support to farmers in case of crop failure due to natural calamities, pests, or diseases, at a low uniform premium rate.',
    shortDesc: 'Low-premium crop insurance against natural calamities and crop failure.',
    level: 'Central',
    authorityName: 'Ministry Of Agriculture and Farmers Welfare',
    ministry: 'Ministry Of Agriculture and Farmers Welfare',
    tags: ['Farmer', 'Agriculture', 'Insurance'],
    categories: ['Agriculture'],
    category: 'Agriculture',
    benefit: 'Crop loss compensation, low premium (1.5%-5%)',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '5.5 Crore+',
    disbursed: '₹1.5 Lakh Cr+',
  },
  {
    id: 'mock-kcc',
    name: 'Kisan Credit Card Scheme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    applyUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    description: 'Provides farmers with timely access to credit for cultivation and other needs at concessional interest rates, with a simplified application and disbursement process.',
    shortDesc: 'Concessional-rate credit card for farmers\' cultivation needs.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Farmer', 'Agriculture', 'Loan', 'Finance'],
    categories: ['Agriculture'],
    category: 'Agriculture',
    benefit: 'Credit up to ₹3 Lakh at 4% interest',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '7 Crore+',
    disbursed: '₹8 Lakh Cr+',
  },
  {
    id: 'mock-soil-health',
    name: 'Soil Health Card Scheme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/soil-health-card',
    applyUrl: 'https://www.myscheme.gov.in/schemes/soil-health-card',
    description: 'Provides farmers with soil nutrient status reports and crop-wise recommendations for appropriate dosage of nutrients to improve productivity through judicious use of fertilizers.',
    shortDesc: 'Free soil testing and fertilizer-use recommendations for farmers.',
    level: 'Central',
    authorityName: 'Ministry Of Agriculture and Farmers Welfare',
    ministry: 'Ministry Of Agriculture and Farmers Welfare',
    tags: ['Farmer', 'Agriculture', 'Soil Health'],
    categories: ['Agriculture'],
    category: 'Agriculture',
    benefit: 'Free soil testing every 2 years',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '22 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-pmksy',
    name: 'PM Krishi Sinchai Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmksy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmksy',
    description: 'Aims to expand irrigation coverage and improve water-use efficiency through micro-irrigation, watershed development, and "Har Khet Ko Pani" initiatives.',
    shortDesc: 'Expands irrigation coverage and water-use efficiency for farms.',
    level: 'Central',
    authorityName: 'Ministry Of Jal Shakti',
    ministry: 'Ministry Of Jal Shakti',
    tags: ['Farmer', 'Agriculture', 'Irrigation'],
    categories: ['Agriculture'],
    category: 'Agriculture',
    benefit: 'Subsidy on micro-irrigation equipment',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '2 Crore+',
    disbursed: '₹90,000 Cr+',
  },

  // ── Healthcare ──────────────────────────────────────────────
  {
    id: 'mock-ayushman-bharat',
    name: 'Ayushman Bharat PM-JAY',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/ab-pmjay',
    applyUrl: 'https://www.myscheme.gov.in/schemes/ab-pmjay',
    description: 'Health insurance scheme providing ₹5 Lakh annual cover per family for secondary and tertiary hospital care, fully government-funded with no premium for beneficiaries.',
    shortDesc: '₹5 Lakh annual health cover per family, no premium required.',
    level: 'Central',
    authorityName: 'Ministry Of Health and Family Welfare',
    ministry: 'Ministry Of Health and Family Welfare',
    tags: ['Healthcare', 'Insurance', 'BPL'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: '₹5 Lakh/year cashless hospital cover',
    deadline: 'Ongoing',
    featured: true,
    totalBeneficiaries: '12 Crore+ families',
    disbursed: '₹1 Lakh Cr+',
  },
  {
    id: 'mock-janani-suraksha',
    name: 'Janani Suraksha Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/jsy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/jsy',
    description: 'Cash assistance for institutional delivery to reduce maternal and infant mortality among pregnant women, especially those from BPL families.',
    shortDesc: 'Cash assistance for institutional childbirth for BPL families.',
    level: 'Central',
    authorityName: 'Ministry Of Health and Family Welfare',
    ministry: 'Ministry Of Health and Family Welfare',
    tags: ['Healthcare', 'Woman', 'Maternity', 'BPL'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: '₹1,400 (rural) / ₹1,000 (urban) cash assistance',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '1 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-pmsma',
    name: 'PM Surakshit Matritva Abhiyan',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmsma',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmsma',
    description: 'Provides free, fixed-day antenatal checkups to pregnant women in their second/third trimester at government health facilities, on the 9th of every month.',
    shortDesc: 'Free monthly antenatal checkups for pregnant women.',
    level: 'Central',
    authorityName: 'Ministry Of Health and Family Welfare',
    ministry: 'Ministry Of Health and Family Welfare',
    tags: ['Healthcare', 'Woman', 'Maternity'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: 'Free antenatal checkups',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '4 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-nhm',
    name: 'National Health Mission',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/nhm',
    applyUrl: 'https://www.myscheme.gov.in/schemes/nhm',
    description: 'Umbrella programme strengthening public health systems, covering rural and urban health infrastructure, disease control programmes, and community health worker networks.',
    shortDesc: 'Strengthens public health infrastructure nationwide.',
    level: 'Central',
    authorityName: 'Ministry Of Health and Family Welfare',
    ministry: 'Ministry Of Health and Family Welfare',
    tags: ['Healthcare'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: 'Access to subsidized public healthcare',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: 'N/A',
    disbursed: '₹36,000 Cr+',
  },

  // ── Education ───────────────────────────────────────────────
  {
    id: 'mock-nmms',
    name: 'National Means-cum-Merit Scholarship',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/nmmss',
    applyUrl: 'https://www.myscheme.gov.in/schemes/nmmss',
    description: 'Scholarship for meritorious students from economically weaker sections to reduce dropout rates at the Class VIII to Class XII level, awarded via a state-level selection exam.',
    shortDesc: 'Merit scholarship for economically weaker Class IX-XII students.',
    level: 'Central',
    authorityName: 'Ministry of Education',
    ministry: 'Ministry of Education',
    tags: ['Student', 'Scholarship', 'Education'],
    categories: ['Education'],
    category: 'Education',
    benefit: '₹12,000 per year',
    deadline: 'Ongoing',
    featured: true,
    totalBeneficiaries: '10 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-postmatric-sc',
    name: 'Post-Matric Scholarship for SC Students',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pms-sc',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pms-sc',
    description: 'Financial assistance to Scheduled Caste students studying at post-matriculation or post-secondary stage, covering tuition fees, maintenance allowance, and other charges.',
    shortDesc: 'Financial aid for SC students in post-matric/post-secondary study.',
    level: 'Central',
    authorityName: 'Ministry Of Social Justice and Empowerment',
    ministry: 'Ministry Of Social Justice and Empowerment',
    tags: ['Student', 'Scholarship', 'Education', 'SC/ST'],
    categories: ['Education'],
    category: 'Education',
    benefit: 'Tuition fees + maintenance allowance',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '60 Lakh+',
    disbursed: '₹6,000 Cr+',
  },
  {
    id: 'mock-yasasvi',
    name: 'PM YASASVI Scholarship',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/yasasvi',
    applyUrl: 'https://www.myscheme.gov.in/schemes/yasasvi',
    description: 'Scholarship for meritorious students from OBC, EBC, and DNT categories, supporting them from Class IX through post-graduation via an entrance test.',
    shortDesc: 'Merit scholarship for OBC/EBC/DNT students, Class IX onward.',
    level: 'Central',
    authorityName: 'Ministry Of Social Justice and Empowerment',
    ministry: 'Ministry Of Social Justice and Empowerment',
    tags: ['Student', 'Scholarship', 'Education', 'OBC'],
    categories: ['Education'],
    category: 'Education',
    benefit: 'Up to ₹1.25 Lakh per year',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '15 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-bbbp',
    name: 'Beti Bachao Beti Padhao',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/bbbp',
    applyUrl: 'https://www.myscheme.gov.in/schemes/bbbp',
    description: 'National campaign to address declining child sex ratio and promote girls\' education, combining awareness generation with multi-sectoral action in select districts.',
    shortDesc: 'National campaign for girl child survival, protection, and education.',
    level: 'Central',
    authorityName: 'Ministry Of Women and Child Development',
    ministry: 'Ministry Of Women and Child Development',
    tags: ['Woman', 'Girl', 'Education', 'Student'],
    categories: ['Education', 'Women & Child'],
    category: 'Education',
    benefit: 'Awareness + district-level support programs',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: 'N/A',
    disbursed: 'N/A',
  },
  {
    id: 'mock-sukanya',
    name: 'Sukanya Samriddhi Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/ssy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/ssy',
    description: 'Small savings scheme for the girl child, offering a high fixed interest rate on deposits made until she turns 21, to support her education and marriage expenses.',
    shortDesc: 'High-interest savings account for a girl child\'s future.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Woman', 'Girl', 'Financial Assistance'],
    categories: ['Women & Child'],
    category: 'Women & Child',
    benefit: 'Fixed high interest rate savings (~8%)',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '3 Crore+ accounts',
    disbursed: 'N/A',
  },

  // ── Housing ─────────────────────────────────────────────────
  {
    id: 'mock-pmay-urban',
    name: 'PM Awas Yojana - Urban',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmay-u',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmay-u',
    description: 'Provides affordable pucca housing to urban poor and EWS/LIG families, including credit-linked subsidy on home loans and direct construction assistance.',
    shortDesc: 'Affordable housing for urban poor, with home loan subsidy.',
    level: 'Central',
    authorityName: 'Ministry Of Housing and Urban Affairs',
    ministry: 'Ministry Of Housing and Urban Affairs',
    tags: ['Housing', 'EWS'],
    categories: ['Housing'],
    category: 'Housing',
    benefit: 'Interest subsidy up to ₹2.67 Lakh',
    deadline: 'Ongoing',
    featured: true,
    totalBeneficiaries: '1.2 Crore+',
    disbursed: '₹2 Lakh Cr+',
  },
  {
    id: 'mock-pmay-gramin',
    name: 'PM Awas Yojana - Gramin',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmay-g',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmay-g',
    description: 'Provides financial assistance for construction of pucca houses to houseless and those living in dilapidated houses in rural areas.',
    shortDesc: 'Financial assistance for pucca housing in rural areas.',
    level: 'Central',
    authorityName: 'Ministry Of Rural Development',
    ministry: 'Ministry Of Rural Development',
    tags: ['Housing', 'Rural'],
    categories: ['Housing'],
    category: 'Housing',
    benefit: '₹1.2 Lakh (plain areas) / ₹1.3 Lakh (hilly)',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '2.9 Crore+',
    disbursed: '₹1.8 Lakh Cr+',
  },
  {
    id: 'mock-clss',
    name: 'Credit Linked Subsidy Scheme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/clss',
    applyUrl: 'https://www.myscheme.gov.in/schemes/clss',
    description: 'Interest subsidy component of PMAY for first-time home buyers from EWS, LIG, and MIG categories availing bank loans for house purchase or construction.',
    shortDesc: 'Home loan interest subsidy for first-time buyers.',
    level: 'Central',
    authorityName: 'Ministry Of Housing and Urban Affairs',
    ministry: 'Ministry Of Housing and Urban Affairs',
    tags: ['Housing', 'Loan'],
    categories: ['Housing'],
    category: 'Housing',
    benefit: 'Interest subsidy on home loans',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '25 Lakh+',
    disbursed: 'N/A',
  },

  // ── Employment / Entrepreneur ───────────────────────────────
  {
    id: 'mock-mudra',
    name: 'PM Mudra Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/mudra',
    applyUrl: 'https://www.myscheme.gov.in/schemes/mudra',
    description: 'Provides collateral-free loans up to ₹10 Lakh to non-corporate, non-farm small and micro enterprises, categorized as Shishu, Kishor, and Tarun.',
    shortDesc: 'Collateral-free loans up to ₹10 Lakh for micro enterprises.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Entrepreneur', 'Business', 'Loan', 'MSME'],
    categories: ['Employment'],
    category: 'Employment',
    benefit: 'Loans up to ₹10 Lakh, no collateral',
    deadline: 'Ongoing',
    featured: true,
    totalBeneficiaries: '40 Crore+',
    disbursed: '₹23 Lakh Cr+',
  },
  {
    id: 'mock-standup-india',
    name: 'Stand-Up India',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/sui',
    applyUrl: 'https://www.myscheme.gov.in/schemes/sui',
    description: 'Facilitates bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST and one woman entrepreneur per bank branch for setting up a greenfield enterprise.',
    shortDesc: 'Bank loans for SC/ST and women entrepreneurs starting a business.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Entrepreneur', 'Business', 'Loan', 'Woman', 'SC/ST'],
    categories: ['Employment'],
    category: 'Employment',
    benefit: 'Loans from ₹10 Lakh to ₹1 Crore',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '2 Lakh+',
    disbursed: '₹40,000 Cr+',
  },
  {
    id: 'mock-pmegp',
    name: 'PM Employment Generation Programme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmegp',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmegp',
    description: 'Credit-linked subsidy programme for generating self-employment through setting up of micro-enterprises in the non-farm sector for unemployed youth and traditional artisans.',
    shortDesc: 'Subsidized self-employment support for youth and artisans.',
    level: 'Central',
    authorityName: 'Ministry Of Micro, Small and Medium Enterprises',
    ministry: 'Ministry Of Micro, Small and Medium Enterprises',
    tags: ['Entrepreneur', 'Business', 'Unemployed', 'Artisan'],
    categories: ['Employment'],
    category: 'Employment',
    benefit: 'Subsidy 15-35% of project cost',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '80 Lakh+',
    disbursed: '₹25,000 Cr+',
  },
  {
    id: 'mock-atal-innovation',
    name: 'Atal Innovation Mission',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/aim',
    applyUrl: 'https://www.myscheme.gov.in/schemes/aim',
    description: 'Promotes innovation and entrepreneurship through Atal Tinkering Labs in schools and Atal Incubation Centres supporting startups across sectors.',
    shortDesc: 'Promotes innovation via school labs and startup incubation centres.',
    level: 'Central',
    authorityName: 'Niti Aayog',
    ministry: 'Niti Aayog',
    tags: ['Entrepreneur', 'Business', 'Student', 'Innovation'],
    categories: ['Employment', 'Education'],
    category: 'Employment',
    benefit: 'Grants up to ₹10 Crore for incubation centres',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '10,000+ Tinkering Labs',
    disbursed: 'N/A',
  },
  {
    id: 'mock-pmkvy',
    name: 'PM Kaushal Vikas Yojana (Skill India)',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmkvy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmkvy',
    description: 'Flagship skill development scheme offering free short-term training and certification aligned to industry needs, with a monetary reward on successful assessment.',
    shortDesc: 'Free short-term skill training and certification for youth.',
    level: 'Central',
    authorityName: 'Ministry Of Skill Development and Entrepreneurship',
    ministry: 'Ministry Of Skill Development and Entrepreneurship',
    tags: ['Student', 'Unemployed', 'Skill Development'],
    categories: ['Employment'],
    category: 'Employment',
    benefit: 'Free training + certification + ₹8,000 reward',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '1.4 Crore+',
    disbursed: 'N/A',
  },

  // ── Women & Child ───────────────────────────────────────────
  {
    id: 'mock-pmmvy',
    name: 'Pradhan Mantri Matru Vandana Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmmvy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmmvy',
    description: 'Maternity benefit programme providing partial wage compensation to women for wage loss during childbirth and to ensure adequate rest and nutrition.',
    shortDesc: 'Maternity cash benefit compensating for wage loss.',
    level: 'Central',
    authorityName: 'Ministry Of Women and Child Development',
    ministry: 'Ministry Of Women and Child Development',
    tags: ['Woman', 'Maternity', 'Financial Assistance'],
    categories: ['Women & Child'],
    category: 'Women & Child',
    benefit: '₹5,000 in installments',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '3.5 Crore+',
    disbursed: '₹13,000 Cr+',
  },
  {
    id: 'mock-ujjwala',
    name: 'Pradhan Mantri Ujjwala Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmuy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmuy',
    description: 'Provides free LPG connections to women from BPL households to replace unclean cooking fuels and reduce health hazards from indoor pollution.',
    shortDesc: 'Free LPG gas connections for BPL women.',
    level: 'Central',
    authorityName: 'Ministry Of Petroleum and Natural Gas',
    ministry: 'Ministry Of Petroleum and Natural Gas',
    tags: ['Woman', 'BPL', 'Rural'],
    categories: ['Women & Child'],
    category: 'Women & Child',
    benefit: 'Free LPG connection + first refill',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '10 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-mahila-shakti',
    name: 'Mahila Shakti Kendra',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/msk',
    applyUrl: 'https://www.myscheme.gov.in/schemes/msk',
    description: 'Empowers rural women through community participation, skill development, employment, digital literacy, and health/nutrition awareness at the block and district level.',
    shortDesc: 'Community-level rural women empowerment and skilling.',
    level: 'Central',
    authorityName: 'Ministry Of Women and Child Development',
    ministry: 'Ministry Of Women and Child Development',
    tags: ['Woman', 'Rural', 'Skill Development'],
    categories: ['Women & Child'],
    category: 'Women & Child',
    benefit: 'Skill training + convergence support',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: 'N/A',
    disbursed: 'N/A',
  },

  // ── Senior Citizens / Pension ───────────────────────────────
  {
    id: 'mock-apy',
    name: 'Atal Pension Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/apy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/apy',
    description: 'Pension scheme for unorganized sector workers guaranteeing a fixed monthly pension of ₹1,000 to ₹5,000 after age 60, based on contribution amount and age at entry.',
    shortDesc: 'Guaranteed monthly pension for unorganized-sector workers.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Senior Citizen', 'Pension', 'Unorganized Sector'],
    categories: ['Senior Citizens'],
    category: 'Senior Citizens',
    benefit: '₹1,000-₹5,000 monthly pension',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '6 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-pmvvy',
    name: 'PM Vaya Vandana Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmvvy',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmvvy',
    description: 'Pension scheme for senior citizens aged 60+ providing an assured return on a lump-sum purchase price, payable monthly, quarterly, half-yearly, or annually.',
    shortDesc: 'Assured-return pension plan for citizens aged 60 and above.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Senior Citizen', 'Pension'],
    categories: ['Senior Citizens'],
    category: 'Senior Citizens',
    benefit: 'Assured ~7.4% annual return',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '7 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-ignoaps',
    name: 'Indira Gandhi National Old Age Pension Scheme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/ignoaps',
    applyUrl: 'https://www.myscheme.gov.in/schemes/ignoaps',
    description: 'Monthly pension for BPL citizens aged 60 and above, higher amount for those 80+, as part of the National Social Assistance Programme.',
    shortDesc: 'Monthly pension for BPL senior citizens.',
    level: 'Central',
    authorityName: 'Ministry Of Rural Development',
    ministry: 'Ministry Of Rural Development',
    tags: ['Senior Citizen', 'Pension', 'BPL'],
    categories: ['Senior Citizens'],
    category: 'Senior Citizens',
    benefit: '₹200-₹500 monthly pension',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '3 Crore+',
    disbursed: 'N/A',
  },

  // ── Insurance ───────────────────────────────────────────────
  {
    id: 'mock-pmjjby',
    name: 'PM Jeevan Jyoti Bima Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmjjby',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmjjby',
    description: 'Renewable term life insurance covering death due to any cause, available to people aged 18-50 at a low annual premium, auto-debited from a linked bank account.',
    shortDesc: 'Low-premium renewable term life insurance for ages 18-50.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Insurance', 'Financial Assistance'],
    categories: ['Insurance'],
    category: 'Insurance',
    benefit: '₹2 Lakh life cover at ₹436/year',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '20 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-pmsby',
    name: 'PM Suraksha Bima Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/pmsby',
    applyUrl: 'https://www.myscheme.gov.in/schemes/pmsby',
    description: 'Accidental death and disability insurance available to people aged 18-70 with a bank account, at a very low annual premium.',
    shortDesc: 'Low-premium accidental death/disability insurance.',
    level: 'Central',
    authorityName: 'Ministry Of Finance',
    ministry: 'Ministry Of Finance',
    tags: ['Insurance', 'Financial Assistance'],
    categories: ['Insurance'],
    category: 'Insurance',
    benefit: '₹2 Lakh cover at ₹20/year',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '35 Crore+',
    disbursed: 'N/A',
  },

  // ── Disability ──────────────────────────────────────────────
  {
    id: 'mock-adip',
    name: 'Assistance to Disabled Persons Scheme (ADIP)',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/adip',
    applyUrl: 'https://www.myscheme.gov.in/schemes/adip',
    description: 'Provides assistive devices and aids to persons with disabilities to promote physical, social, and economic rehabilitation, distributed free or at highly subsidized rates.',
    shortDesc: 'Free/subsidized assistive devices for persons with disabilities.',
    level: 'Central',
    authorityName: 'Ministry Of Social Justice and Empowerment',
    ministry: 'Ministry Of Social Justice and Empowerment',
    tags: ['Disabled', 'PwD', 'Assistive Devices'],
    categories: ['Disability'],
    category: 'Disability',
    benefit: 'Free/subsidized assistive aids',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '15 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-accessible-india',
    name: 'Accessible India Campaign',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/aic',
    applyUrl: 'https://www.myscheme.gov.in/schemes/aic',
    description: 'National campaign to achieve universal accessibility for persons with disabilities across the built environment, transportation, and information/communication ecosystems.',
    shortDesc: 'Nationwide push for universal accessibility infrastructure.',
    level: 'Central',
    authorityName: 'Ministry Of Social Justice and Empowerment',
    ministry: 'Ministry Of Social Justice and Empowerment',
    tags: ['Disabled', 'PwD', 'Accessibility'],
    categories: ['Disability'],
    category: 'Disability',
    benefit: 'Accessibility infrastructure upgrades',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: 'N/A',
    disbursed: 'N/A',
  },

  // ── State schemes ───────────────────────────────────────────
  {
    id: 'mock-gj-yuva-swavalamban',
    name: 'Mukhyamantri Yuva Swavalamban Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/mysy-gj',
    applyUrl: 'https://www.myscheme.gov.in/schemes/mysy-gj',
    description: 'Gujarat state scheme providing scholarships and tuition fee assistance to meritorious students from economically weaker families pursuing higher education.',
    shortDesc: 'Gujarat: scholarship + tuition assistance for meritorious students.',
    level: 'State',
    authorityName: 'Gujarat',
    ministry: 'Gujarat',
    tags: ['Student', 'Scholarship', 'Education'],
    categories: ['Education'],
    category: 'Education',
    benefit: 'Tuition fee assistance up to ₹50,000',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '5 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-mh-jan-arogya',
    name: 'Mahatma Jyotiba Phule Jan Arogya Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/mjpjay',
    applyUrl: 'https://www.myscheme.gov.in/schemes/mjpjay',
    description: 'Maharashtra state health insurance scheme providing cashless treatment for over 900 medical procedures to economically vulnerable families.',
    shortDesc: 'Maharashtra: cashless health insurance for vulnerable families.',
    level: 'State',
    authorityName: 'Maharashtra',
    ministry: 'Maharashtra',
    tags: ['Healthcare', 'Insurance', 'BPL'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: '₹1.5 Lakh cashless cover per family',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '2 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-up-kanya-sumangala',
    name: 'Kanya Sumangala Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/mksy-up',
    applyUrl: 'https://www.myscheme.gov.in/schemes/mksy-up',
    description: 'Uttar Pradesh scheme providing financial assistance in installments from birth through graduation to support the girl child\'s upbringing and education.',
    shortDesc: 'UP: staged financial support for the girl child, birth to graduation.',
    level: 'State',
    authorityName: 'Uttar Pradesh',
    ministry: 'Uttar Pradesh',
    tags: ['Woman', 'Girl', 'Student', 'Financial Assistance'],
    categories: ['Women & Child'],
    category: 'Women & Child',
    benefit: '₹25,000 total across 6 installments',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '25 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-rj-bhamashah',
    name: 'Bhamashah Swasthya Bima Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/bsby',
    applyUrl: 'https://www.myscheme.gov.in/schemes/bsby',
    description: 'Rajasthan state health insurance scheme providing cashless treatment at empaneled hospitals for BPL and NFSA-eligible families.',
    shortDesc: 'Rajasthan: cashless health insurance for eligible families.',
    level: 'State',
    authorityName: 'Rajasthan',
    ministry: 'Rajasthan',
    tags: ['Healthcare', 'Insurance', 'BPL'],
    categories: ['Healthcare'],
    category: 'Healthcare',
    benefit: '₹3 Lakh cashless cover per family',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '1 Crore+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-ka-vidyasiri',
    name: 'Vidyasiri Scholarship',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/vidyasiri',
    applyUrl: 'https://www.myscheme.gov.in/schemes/vidyasiri',
    description: 'Karnataka state scholarship providing maintenance allowance to SC/ST/OBC/minority students pursuing professional and technical courses who are not availing hostel facilities.',
    shortDesc: 'Karnataka: maintenance allowance for SC/ST/OBC/minority students.',
    level: 'State',
    authorityName: 'Karnataka',
    ministry: 'Karnataka',
    tags: ['Student', 'Scholarship', 'SC/ST', 'OBC'],
    categories: ['Education'],
    category: 'Education',
    benefit: '₹15,500 - ₹20,000 per year',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '2 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-wb-kanyashree',
    name: 'Kanyashree Prakalpa',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/kanyashree',
    applyUrl: 'https://www.myscheme.gov.in/schemes/kanyashree',
    description: 'West Bengal conditional cash transfer scheme to improve the status of girls, incentivizing school attendance and delaying marriage until legal age.',
    shortDesc: 'West Bengal: cash incentive for girls to stay in school.',
    level: 'State',
    authorityName: 'West Bengal',
    ministry: 'West Bengal',
    tags: ['Woman', 'Girl', 'Student', 'Education'],
    categories: ['Women & Child', 'Education'],
    category: 'Women & Child',
    benefit: 'Annual scholarship + one-time grant at 18',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '80 Lakh+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-tn-amma-twowheeler',
    name: 'Amma Two Wheeler Scheme',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/amma-two-wheeler',
    applyUrl: 'https://www.myscheme.gov.in/schemes/amma-two-wheeler',
    description: 'Tamil Nadu state scheme providing a 50% subsidy on two-wheeler purchase for working women to improve mobility and access to employment.',
    shortDesc: 'Tamil Nadu: 50% subsidy on two-wheelers for working women.',
    level: 'State',
    authorityName: 'Tamil Nadu',
    ministry: 'Tamil Nadu',
    tags: ['Woman', 'Employment'],
    categories: ['Employment'],
    category: 'Employment',
    benefit: '50% subsidy, up to ₹25,000',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '70,000+',
    disbursed: 'N/A',
  },
  {
    id: 'mock-dl-tirth-yatra',
    name: 'Mukhyamantri Tirth Yatra Yojana',
    sourceUrl: 'https://www.myscheme.gov.in/schemes/cmtyy-dl',
    applyUrl: 'https://www.myscheme.gov.in/schemes/cmtyy-dl',
    description: 'Delhi state scheme providing free pilgrimage travel, including transport, lodging, and meals, to senior citizens over 60 years of age.',
    shortDesc: 'Delhi: free pilgrimage travel for senior citizens.',
    level: 'State',
    authorityName: 'Delhi',
    ministry: 'Delhi',
    tags: ['Senior Citizen', 'Pilgrimage'],
    categories: ['Senior Citizens'],
    category: 'Senior Citizens',
    benefit: 'Free travel, lodging, and meals',
    deadline: 'Ongoing',
    featured: false,
    totalBeneficiaries: '1 Lakh+',
    disbursed: 'N/A',
  },
];
