// Static translated phrases for eligibility and required documents
export const PHRASES = {
  en: {
  "residentOfGujarat": "Must be a permanent resident of Gujarat state.",
  "citizenOfIndia": "Must be a citizen of India.",
  "enrolledInInstitution": "Must be currently enrolled in a recognized educational institution.",
  "maintainAttendance": "Must maintain minimum attendance or pass percentage as prescribed by the institution.",
  "activeFarmer": "Must be an active farmer (landowner, tenant, or agricultural laborer).",
  "validFarmerCard": "Must hold a valid farmer identity card or land records.",
  "femaleOnly": "Applicable exclusively for female candidates/households.",
  "disabilityCertificate": "Must possess a disability certificate with 40% or more disability.",
  "incomeLimit": "Family annual income must be within the threshold limits (e.g., up to ₹2.5 Lakhs or as applicable).",
  "aadhaarCard": "Aadhaar Card",
  "passportPhoto": "Passport Size Photograph",
  "domicileProof": "Gujarat Domicile / Residence Proof",
  "identityProof": "Identity & Address Proof",
  "incomeCertificate": "Income Certificate",
  "schoolId": "School/College ID Card",
  "marksheet": "Previous Year Marksheet / Progress Report",
  "feeReceipt": "Fee Receipt of current academic year",
  "landRecords": "Land Ownership Documents (7/12 extract)",
  "farmerCard": "Farmer Identity Card",
  "disabilityCard": "Disability Certificate (UDID Card)",
  "bankPassbook": "Active Bank Account Passbook (linked with Aadhaar)"
},
  hi: {
  "residentOfGujarat": "गुजरात राज्य का स्थायी निवासी होना चाहिए।",
  "citizenOfIndia": "भारत का नागरिक होना चाहिए।",
  "enrolledInInstitution": "मान्यता प्राप्त शैक्षिक संस्थान में वर्तमान में दाखिला लिया हुआ होना चाहिए।",
  "maintainAttendance": "संस्थान द्वारा निर्धारित न्यूनतम उपस्थिति या पास प्रतिशत बनाए रखना चाहिए।",
  "activeFarmer": "एक सक्रिय किसान (भूमि मालिक, किरायेदार या कृषि मजदूर) होना चाहिए।",
  "validFarmerCard": "वैध किसान पहचान पत्र या भूमि रिकॉर्ड होना चाहिए।",
  "femaleOnly": "केवल महिला उम्मीदवारों/परिवारों के लिए लागू होता है।",
  "disabilityCertificate": "40% या अधिक विकलांगता का प्रमाण पत्र होना चाहिए।",
  "incomeLimit": "परिवार की वार्षिक आय सीमा के भीतर होनी चाहिए (उदाहरण के लिए, ₹2.5 लाख तक या लागू होने के अनुसार)।",
  "aadhaarCard": "आधार कार्ड",
  "passportPhoto": "पासपोर्ट आकार की फोटो",
  "domicileProof": "गुजरात निवास/आवास प्रमाण",
  "identityProof": "पहचान और पता प्रमाण",
  "incomeCertificate": "आय प्रमाण पत्र",
  "schoolId": "स्कूल/कॉलेज आईडी कार्ड",
  "marksheet": "पिछले वर्ष की मार्कशीट/प्रगति रिपोर्ट",
  "feeReceipt": "वर्तमान शैक्षणिक वर्ष की फीस रसीद",
  "landRecords": "भूमि स्वामित्व दस्तावेज (7/12 निकाल)",
  "farmerCard": "किसान पहचान पत्र",
  "disabilityCard": "विकलांगता प्रमाण पत्र (यूडीआईडी कार्ड)",
  "bankPassbook": "सक्रिय बैंक खाता पासबुक (आधार से जुड़ा हुआ)"
},
  gu: {
  "residentOfGujarat": "ગુજરાત રાજ્યના સ્થાયી રહેવાસી હોવો જોઈએ.",
  "citizenOfIndia": "ભારતનો નાગરિક હોવો જોઈએ.",
  "enrolledInInstitution": "માન્યતા પ્રાપ્ત શૈક્ષણિક સંસ્થામાં હાલમાં દાખલો લીધેલો હોવો જોઈએ.",
  "maintainAttendance": "સંસ્થા દ્વારા નિર્ધારિત હાજરી અથવા પાસની ટકાવારી જાળવી રાખવી જોઈએ.",
  "activeFarmer": "સક્રિય ખેડૂત (જમીનનો માલિક, ભાડૂત અથવા ખેતી મજૂર) હોવો જોઈએ.",
  "validFarmerCard": "માન્ય ખેડૂત ઓળખ કાર્ડ અથવા જમીન રેકોર્ડ ધરાવતો હોવો જોઈએ.",
  "femaleOnly": "માત્ર મહિલા ઉમેદવારો/પરિવારો માટે લાગુ પડે છે.",
  "disabilityCertificate": "40% અથવા તેથી વધુ અક્ષમતા સાથે અક્ષમતા પ્રમાણપત્ર ધરાવતો હોવો જોઈએ.",
  "incomeLimit": "પરિવારની વાર્ષિક આવક મર્યાદામાં હોવી જોઈએ (ઉદાહરણ તરીકે, ₹2.5 લાખ સુધી અથવા જે લાગુ પડે).",
  "aadhaarCard": "આધાર કાર્ડ",
  "passportPhoto": "પાસપોર્ટ કદનું ફોટોગ્રાફ",
  "domicileProof": "ગુજરાત નિવાસ/રહેઠાણ પુરાવો",
  "identityProof": "ઓળખ અને સરનામું પુરાવો",
  "incomeCertificate": "આવક પ્રમાણપત્ર",
  "schoolId": "શાળા/કોલેજ આઈડી કાર્ડ",
  "marksheet": "અગાઉના વર્ષનું માર્કશીટ / પ્રગતિ અહેવાલ",
  "feeReceipt": "હાલના શૈક્ષણિક વર્ષનો ફી રસીદ",
  "landRecords": "જમીન માલિકીના દસ્તાવેજ (7/12 ઉતારો)",
  "farmerCard": "ખેડૂત ઓળખ કાર્ડ",
  "disabilityCard": "અક્ષમતા પ્રમાણપત્ર (યુડીઆઈડી કાર્ડ)",
  "bankPassbook": "સક્રિય બેંક ખાતાનું પાસબુક (આધાર સાથે જોડાયેલ)"
}
};
