import { Scheme } from '../types';

export const SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    title: 'PM Kisan Samman Nidhi',
    category: 'Agriculture',
    categoryColor: 'secondary-container',
    categoryTextColor: 'on-secondary-container',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    level: 'Central',
    status: 'Active',
    benefit: '₹6,000/year (3 installments of ₹2,000)',
    deadline: 'Ongoing',
    shortDesc: 'Direct income support of ₹6,000 per year for farmer families across India in three equal installments.',
    description: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi) is a Central Sector Scheme that provides income support to all landholding farmer families across India. The scheme transfers ₹6,000 per year in three equal installments directly into bank accounts via Direct Benefit Transfer (DBT).',
    eligibility: ['Must be a landholding farmer family', 'Own cultivable land', 'Income below ₹2 lakh/year (institutional exceptions)', 'Valid Aadhaar card', 'Active bank account linked to Aadhaar'],
    documents: ['Aadhaar Card', 'Land Records (Khasra/Khatauni)', 'Bank Account Passbook', 'Mobile Number'],
    applyUrl: 'https://pmkisan.gov.in',
    tags: ['Land Owner', 'Rural', 'Farmers'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPXzE3tvQ5ua6uK5_2rHMrPqs_t2EzrTE5g9pzLxtV9SykRrFP-uFHUz84IgofyLe2tIIuiYzHShm3sgK2y6_crGBqnHmtS7cpkiJ7WWacsZyISfRVP4Iq-1b_Bll4RI8e0iKvmvmkoMbDmr-5rOm5_2Ma6awRj50gj-qKId7MMAE0V9WseH14fIbkyYaF0GSH78hMrX7fAMUViZEeZMLlAXLUx4URXhFqV311psQxRNMzwi2HtJ9a',
    featured: true,
    totalBeneficiaries: '11.8 Crore',
    disbursed: '₹2.81 Lakh Crore',
  },
  {
    id: 'ayushman-bharat',
    title: 'Ayushman Bharat — PM-JAY',
    category: 'Healthcare',
    categoryColor: 'primary-fixed',
    categoryTextColor: 'on-primary-fixed',
    ministry: 'Ministry of Health & Family Welfare',
    level: 'Central',
    status: 'Active',
    benefit: '₹5 Lakh health cover per family/year',
    deadline: 'Ongoing',
    shortDesc: "World's largest health insurance scheme providing ₹5 lakh cover per family per year for hospitalization.",
    description: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY) is the world's largest health assurance scheme. It provides cashless cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization at empanelled hospitals.",
    eligibility: ['BPL/SECC database family', 'No income cap for SECC listed families', 'Valid Aadhaar or ration card', 'Covers pre-existing conditions from day 1'],
    documents: ['Aadhaar Card', 'Ration Card (for SECC families)', 'PM-JAY e-card (auto-generated)'],
    applyUrl: 'https://pmjay.gov.in',
    tags: ['BPL Families', 'Health Cover', 'Hospitalization'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsQiusbadFdy9DTGoMzYQjZ3QdxqAJ71NkXOEgjT-6wHFUeMh46MZyLr3cMPijsWONmjKjO2eKp78ABfT2Bq9i8BD8Hw4xg1DG1OqAMsoRNOxz6gFZYyYTycMUhb2n4iLruNXII8R7nhTpalV5rFAilImu53tv8bb9aocgDMMeTqRnNBlce1nRJYiyIkSSPv70I8O0EGWGhMscsDzZlNuoEslqf2gMU8c8_5a-pBxY_aYbL59dBXIq',
    featured: false,
    totalBeneficiaries: '55 Crore',
    disbursed: '₹79,000 Crore',
  },
  {
    id: 'post-matric-scholarship-sc',
    title: 'Post-Matric Scholarship for SC Students',
    category: 'Education',
    categoryColor: 'tertiary-fixed',
    categoryTextColor: 'on-tertiary-fixed',
    ministry: 'Ministry of Social Justice & Empowerment',
    level: 'Central',
    status: 'Active',
    benefit: 'Maintenance allowance + course fees',
    deadline: 'Ends in 12 days',
    deadlineUrgent: true,
    shortDesc: 'Financial assistance to Scheduled Caste students at post-matriculation or post-secondary stages.',
    description: 'This scholarship enables Scheduled Caste students to pursue post-matriculation education by covering maintenance allowance and reimbursement of compulsory fees charged by educational institutions.',
    eligibility: ['Belongs to Scheduled Caste category', 'Studying at Class XI or higher', 'Parental income below ₹2.5 lakh/year', 'Not availing any other scholarship'],
    documents: ['Caste Certificate (SC)', 'Income Certificate', 'Previous Marksheet', 'Aadhaar Card', 'Bank Account Details', 'Institution Bonafide Certificate'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Income < 2.5L', 'SC Category', 'Pan India'],
    image: '',
    featured: false,
    totalBeneficiaries: '60 Lakh',
    disbursed: '₹3,500 Crore',
  },
  {
    id: 'pm-awas-yojana-urban',
    title: 'PM Awas Yojana (Urban)',
    category: 'Housing',
    categoryColor: 'secondary-container',
    categoryTextColor: 'on-secondary-container',
    ministry: 'Ministry of Housing & Urban Affairs',
    level: 'Central',
    status: 'Active',
    benefit: 'Up to ₹2.67 Lakh subsidy on home loan interest',
    deadline: 'Ongoing',
    shortDesc: 'Providing affordable housing for all urban poor with credit-linked subsidies and direct assistance.',
    description: 'PMAY-Urban aims to provide affordable housing to all urban poor. The scheme offers credit-linked subsidy on home loans for EWS, LIG, and MIG categories, and direct construction assistance for slum dwellers.',
    eligibility: ['Urban area resident', 'Does not own a pucca house', 'EWS: income up to ₹3L | LIG: ₹3-6L | MIG: ₹6-18L', 'First-time home buyer (family)', 'Aadhaar mandatory'],
    documents: ['Aadhaar Card', 'Income Certificate', 'Affidavit of no pucca house', 'Property documents', 'Bank account', 'Caste certificate (if applicable)'],
    applyUrl: 'https://pmaymis.gov.in',
    tags: ['Urban Poor', 'Housing', 'Subsidy'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkKlYMR3wMfgzXNcpUZL9_2m0hdoYTuQ6tCeAfLM1qOw1RLlktx40pqNHA6GgLzPCRl8XTy4EAeFKgfB8Ovu-aiBDvGSyGhwr_Cmu30thReVqfjygZU5OKa-wZ5GY7jQxULTGM-O9yokHy__ZTB7p4E_TtXH3avZtv79cHGQKOYoyn4fweGxi3865IPnPbGtsxTI7SIDyFkuW1YCaFZ2j8_X_23hOspIB_gb0U6CZKnrgw3TaiIE_',
    featured: true,
    totalBeneficiaries: '1.2 Crore',
    disbursed: '₹1.5 Lakh Crore',
  },
  {
    id: 'digital-india-internship',
    title: 'Digital India Internship',
    category: 'Employment',
    categoryColor: 'tertiary-container',
    categoryTextColor: 'on-tertiary-container',
    ministry: 'Ministry of Electronics & IT (MeitY)',
    level: 'Central',
    status: 'New Listing',
    benefit: '₹10,000/month stipend for 2 months',
    deadline: 'Ongoing',
    shortDesc: 'Paid internship opportunities at MeitY and its organizations for engineering students.',
    description: 'The Digital India Internship Scheme provides hands-on experience to students in engineering and technology domains at Ministry of Electronics and IT. Selected interns work on live digital India projects.',
    eligibility: ['B.Tech/B.E./M.Tech student', 'CGPA above 6.5', 'Indian citizen', 'Age 18-30 years', 'Not placed through campus'],
    documents: ['College ID', 'Bonafide Certificate', 'Resume/CV', 'Aadhaar Card', 'Bank Details'],
    applyUrl: 'https://meity.gov.in/content/digital-india-internship-scheme',
    tags: ['Students', 'Tech', 'Employment'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5wEM5Pnc_COZlBJ6KXZJtMiPPXh0bwq06rJK35DltSHXgaXyEQPKU3fg72ca-n4d6R7aamqgse4U6VPpUkbuPg90dRnYG3hAzzu-i0p09utAMesg5wirIzWH8a1_fzNkFOkxiUL4K17yxHWHwOYExP3TMEZue8vSIX5-N_Fy-g0lOVQS2t9CR8B2dzq84YaDSDDplTHGAXVlwYGTnff383fUR1vZU8Gb45K8EdgsiampBiZK9Tv9F',
    featured: true,
    totalBeneficiaries: '5,000/year',
    disbursed: 'N/A',
  },
  {
    id: 'nmmss',
    title: 'National Means Cum Merit Scholarship',
    category: 'Education',
    categoryColor: 'tertiary-fixed',
    categoryTextColor: 'on-tertiary-fixed',
    ministry: 'Ministry of Education',
    level: 'Central',
    status: 'Active',
    benefit: '₹12,000/year (Class IX–XII)',
    deadline: 'Ends in 4 days',
    deadlineUrgent: true,
    shortDesc: 'Scholarship for meritorious students of economically weaker sections to continue education.',
    description: 'NMMSS aims to award scholarships to meritorious students of economically weaker sections to arrest drop-out at Class VIII stage. Continued from Class IX to XII through annual renewal.',
    eligibility: ['Studying in Class IX or higher', 'Passed Class VIII exam with at least 55% marks', 'Parental income below ₹3.5 lakh/year', 'Government/aided school student'],
    documents: ['Class VIII Marksheet', 'Income Certificate', 'Aadhaar Card', 'School Enrollment Certificate', 'Bank Account'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Class IX-XII', 'Merit Based', 'Economically Weaker'],
    image: '',
    featured: false,
    totalBeneficiaries: '1 Lakh',
    disbursed: '₹1,200 Crore',
  },
  {
    id: 'solar-rooftop-subsidy',
    title: 'PM Surya Ghar: Solar Rooftop Subsidy',
    category: 'Environment',
    categoryColor: 'tertiary-fixed',
    categoryTextColor: 'on-tertiary-fixed',
    ministry: 'Ministry of New & Renewable Energy',
    level: 'Central',
    status: 'Active',
    benefit: 'Up to 40% subsidy (up to 3kW)',
    deadline: 'Ongoing',
    shortDesc: 'Get up to 40% subsidy on installation of solar panels at your residence to reduce electricity bills.',
    description: 'PM Surya Ghar: Muft Bijli Yojana provides free electricity up to 300 units/month by subsidizing solar panel installations. Subsidies range from 40% (up to 2kW) to 20% (2-3kW additional capacity).',
    eligibility: ['Indian citizen', 'Residential property owner', 'Valid electricity connection', 'No prior solar subsidy availed'],
    documents: ['Electricity bill', 'Property ownership proof', 'Aadhaar Card', 'Bank account', 'Net metering agreement from DISCOM'],
    applyUrl: 'https://pmsuryaghar.gov.in',
    tags: ['Homeowner', 'Energy', 'Green'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCtkKlYMR3wMfgzXNcpUZL9_2m0hdoYTuQ6tCeAfLM1qOw1RLlktx40pqNHA6GgLzPCRl8XTy4EAeFKgfB8Ovu-aiBDvGSyGhwr_Cmu30thReVqfjygZU5OKa-wZ5GY7jQxULTGM-O9yokHy__ZTB7p4E_TtXH3avZtv79cHGQKOYoyn4fweGxi3865IPnPbGtsxTI7SIDyFkuW1YCaFZ2j8_X_23hOspIB_gb0U6CZKnrgw3TaiIE_',
    featured: false,
    totalBeneficiaries: '1 Crore target',
    disbursed: '₹75,000 Crore budgeted',
  },
  {
    id: 'startup-india-seed-fund',
    title: 'Startup India Seed Fund',
    category: 'Employment',
    categoryColor: 'tertiary-container',
    categoryTextColor: 'on-tertiary-container',
    ministry: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    level: 'Central',
    status: 'Active',
    benefit: 'Up to ₹20 Lakh for proof-of-concept; ₹50 Lakh for commercialization',
    deadline: 'Rolling',
    shortDesc: 'Financial assistance for early-stage entrepreneurs to build and validate innovative business ideas.',
    description: 'Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization via DPIIT-recognized incubators.',
    eligibility: ['DPIIT-recognized startup', 'Incorporated less than 2 years ago', 'Not received more than ₹10L funding previously', 'Innovative product/service', 'Scalable business model'],
    documents: ['DPIIT Recognition Certificate', 'Incorporation Certificate', 'Business Plan', 'Founder Aadhaar', 'Bank Account'],
    applyUrl: 'https://seedfund.startupindia.gov.in',
    tags: ['Startup', 'Entrepreneur', 'Innovation'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5wEM5Pnc_COZlBJ6KXZJtMiPPXh0bwq06rJK35DltSHXgaXyEQPKU3fg72ca-n4d6R7aamqgse4U6VPpUkbuPg90dRnYG3hAzzu-i0p09utAMesg5wirIzWH8a1_fzNkFOkxiUL4K17yxHWHwOYExP3TMEZue8vSIX5-N_Fy-g0lOVQS2t9CR8B2dzq84YaDSDDplTHGAXVlwYGTnff383fUR1vZU8Gb45K8EdgsiampBiZK9Tv9F',
    featured: false,
    totalBeneficiaries: '3,600 startups',
    disbursed: '₹945 Crore',
  },
  {
    id: 'pradhan-mantri-matru-vandana',
    title: 'Pradhan Mantri Matru Vandana Yojana',
    category: 'Women & Child',
    categoryColor: 'error-container',
    categoryTextColor: 'on-error-container',
    ministry: 'Ministry of Women & Child Development',
    level: 'Central',
    status: 'Active',
    benefit: '₹6,500 maternity benefit (total)',
    deadline: 'Ongoing',
    shortDesc: 'Maternity benefit for pregnant and lactating women for their first living child, promoting institutional delivery.',
    description: 'PMMVY provides a cash incentive of ₹5,000 in three installments to pregnant and lactating women for the first living child. An additional ₹1,000 is given through the Janani Suraksha Yojana for institutional delivery.',
    eligibility: ['Pregnant/lactating woman', 'First living child', 'Age 19 years or above', 'Not a Central/State Government employee', 'Aadhaar linked to bank account'],
    documents: ['Aadhaar Card', 'MCP (Mother and Child Protection) Card', 'Bank Account Passbook', 'Identity Proof'],
    applyUrl: 'https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana',
    tags: ['Women', 'Maternity', 'Health'],
    image: '',
    featured: false,
    totalBeneficiaries: '3.5 Crore',
    disbursed: '₹17,000 Crore',
  },
  {
    id: 'indira-gandhi-national-old-age-pension',
    title: 'Indira Gandhi National Old Age Pension',
    category: 'Senior Citizens',
    categoryColor: 'surface-container',
    categoryTextColor: 'on-surface-variant',
    ministry: 'Ministry of Rural Development',
    level: 'Central',
    status: 'Active',
    benefit: '₹200-500/month pension',
    deadline: 'Ongoing',
    shortDesc: 'Monthly pension for BPL elderly citizens aged 60 years and above, to support their livelihood.',
    description: 'IGNOAPS provides monthly pension assistance of ₹200 (age 60-79) and ₹500 (age 80+) to BPL senior citizens. State governments often add top-up amounts.',
    eligibility: ['Age 60 years or above', 'Below Poverty Line (BPL)', 'Aadhaar card mandatory', 'Annual income below state poverty line'],
    documents: ['Age Proof (Birth Certificate/School Certificate)', 'BPL Card/Ration Card', 'Aadhaar Card', 'Bank Account Passbook', 'Income Certificate'],
    applyUrl: 'https://nsap.nic.in',
    tags: ['Senior Citizens', 'Pension', 'BPL'],
    image: '',
    featured: false,
    totalBeneficiaries: '2.5 Crore',
    disbursed: '₹9,000 Crore/year',
  },
  {
    id: 'pmegp',
    title: 'Prime Minister Employment Generation Programme',
    category: 'Employment',
    categoryColor: 'tertiary-container',
    categoryTextColor: 'on-tertiary-container',
    ministry: 'Ministry of MSME',
    level: 'Central',
    status: 'Active',
    benefit: '15-35% government subsidy on project cost',
    deadline: 'Ongoing',
    shortDesc: 'Credit-linked subsidy for setting up micro enterprises in non-farm sector to generate employment.',
    description: 'PMEGP helps unemployed youth and traditional artisans to set up micro enterprises. It provides bank finance with government subsidy (15% to 35% of project cost) for manufacturing and service sector projects.',
    eligibility: ['Age 18 years and above', 'Minimum Class VIII pass for projects above ₹10L', 'No prior assistance under similar scheme', 'Self-help groups, cooperatives, trusts also eligible'],
    documents: ['Aadhaar Card', 'Educational Qualification Certificate', 'EDP (Entrepreneurship Development Programme) Certificate', 'Project Report', 'Bank Account'],
    applyUrl: 'https://www.kviconline.gov.in/pmegpeportal',
    tags: ['Entrepreneur', 'MSME', 'Self-Employment'],
    image: '',
    featured: false,
    totalBeneficiaries: '8 Lakh',
    disbursed: '₹19,000 Crore',
  },
  {
    id: 'sukanya-samriddhi',
    title: 'Sukanya Samriddhi Yojana',
    category: 'Women & Child',
    categoryColor: 'error-container',
    categoryTextColor: 'on-error-container',
    ministry: 'Ministry of Finance',
    level: 'Central',
    status: 'Active',
    benefit: '8.2% p.a. interest + tax benefits (Section 80C)',
    deadline: 'Ongoing',
    shortDesc: "Small savings scheme for girl child's future education and marriage expenses with tax benefits.",
    description: "Sukanya Samriddhi Yojana is a small savings scheme for the girl child. A parent/guardian can open an account for a girl below 10 years of age. The account matures 21 years from opening or on marriage after 18, with one of the highest interest rates among small savings schemes.",
    eligibility: ['Girl child below 10 years of age', 'Indian citizen', 'One account per girl (max 2 daughters)', 'Deposit range: ₹250 to ₹1.5 Lakh/year'],
    documents: ["Birth Certificate of girl child", "Parent/Guardian Aadhaar", "Parent/Guardian PAN Card", "Address Proof"],
    applyUrl: 'https://www.indiapost.gov.in',
    tags: ['Girl Child', 'Savings', 'Tax Benefit'],
    image: '',
    featured: false,
    totalBeneficiaries: '3 Crore accounts',
    disbursed: 'N/A',
  },
];
