import { FieldResult } from './translator.js';

/**
 * Translates a list of short labels (ministry names, tags) in small batches, with a second chance for
 * anything that fails: if a batch is rejected by the validator, each label in it is retried on its own, so
 * one stubborn label can't take the whole batch down. Labels that still fail are returned in `failed`
 * rather than guessed at.
 */
export type TranslateBatch = (items: string[]) => Promise<FieldResult>;

export interface BuildResult {
  translated: Record<string, string>;
  /** Which model produced each label ("a+b" means more than one was used), for the review file. */
  models: Record<string, string>;
  /** Labels that needed a retry on their own, or more than one attempt: worth a human look. */
  retried: string[];
  failed: Array<{ term: string; error: string }>;
}

const BATCH_SIZE = 20;

export async function translateTerms(terms: string[], translate: TranslateBatch): Promise<BuildResult> {
  const out: BuildResult = { translated: {}, models: {}, retried: [], failed: [] };

  for (let i = 0; i < terms.length; i += BATCH_SIZE) {
    const batch = terms.slice(i, i + BATCH_SIZE);
    const r = await translate(batch);
    if (r.ok && Array.isArray(r.value) && r.value.length === batch.length) {
      batch.forEach((term, j) => {
        out.translated[term] = (r.value as string[])[j].trim();
        out.models[term] = r.model ?? '';
        if (r.model?.includes('+')) out.retried.push(term);
      });
      continue;
    }
    for (const term of batch) {
      const single = await translate([term]);
      if (single.ok && Array.isArray(single.value) && single.value.length === 1) {
        out.translated[term] = (single.value as string[])[0].trim();
        out.models[term] = single.model ?? '';
        out.retried.push(term);
      } else {
        out.failed.push({ term, error: single.error ?? 'rejected' });
      }
    }
  }
  return out;
}

/** The generated data file, with keys sorted so a rerun produces a small, readable diff. */
export function renderVocabularyFile(exportName: string, names: Record<string, string>, tags: Record<string, string>): string {
  const body = (m: Record<string, string>) =>
    Object.keys(m)
      .sort((a, b) => a.localeCompare(b, 'en'))
      .map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(m[k])},`)
      .join('\n');
  return [
    "import type { VocabularyData } from '../vocabulary.js';",
    '',
    `// Generated by \`npm run translate:vocabulary -- ${exportName}\`. Safe to hand-edit: a rerun keeps entries that are`,
    '// already here and only translates what is missing.',
    `export const ${exportName}: VocabularyData = {`,
    '  names: {',
    body(names),
    '  },',
    '  tags: {',
    body(tags),
    '  },',
    '};',
    '',
  ].join('\n');
}
